version: "3"

networks:
  loki:

services:
  app_python:
    image: lizavetta/devops-python:latest
    ports:
      - "8082:80"
    logging: &logging
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}"
    networks:
      - loki

  app_javascript:
    image: lizavetta/devops-svelte:latest
    ports:
      - "80:80"
    logging: *logging
    networks:
      - loki


  loki:
    container_name: loki
    image: grafana/loki:2.9.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    logging: *logging
    networks:
      - loki

  promtail:
    container_name: promtail
    image: grafana/promtail:2.9.1
    volumes:
      - /var/log:/var/log
      - /var/lib:/var/lib
      - /Users/elizaveta/Desktop/devops/monitoring/promtail/promtail.yml:/etc/promtail/promtail.yml

    command: -config.file=/etc/promtail/config.yml
    logging: *logging
    networks:
      - loki

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    logging: *logging
    networks:
      - loki
    depends_on:
      - loki