name: Python package

on:
  push:
    paths:
      - '.github/workflows/python-app.yaml'
      - 'app_python/**'
      - '!app_python/**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          cd app_python
          python -m pip install --upgrade pip
          pip install ruff pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Linter
          run: |
            cd app_python
            pylint app/main.py

      - name: Test with pytest
        run: |
          cd app_python
          pytest

      - name: SNYK install
       run: |
         npm install snyk@latest -g

      - name: Snyk Test
        run: |
          cd app_python
          snyk test --all-projects --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
